#!/bin/bash
# docgen — extract pub fn signatures + leading doc comments from each orb
# into docs/orbs/<orb>.md.
#
# Convention: a `pub fn name(params) -> ret:` line is documented by the
# contiguous `# ...` comment block immediately above it.

set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT_DIR="$ROOT/docs/orbs"
mkdir -p "$OUT_DIR"

INDEX="$OUT_DIR/index.md"
echo "# Orion stdlib reference" > "$INDEX"
echo "" >> "$INDEX"
echo "Auto-generated by tools/docgen.sh — do NOT hand-edit." >> "$INDEX"
echo "" >> "$INDEX"

for orb_dir in "$ROOT/orbs"/*/; do
    orb=$(basename "$orb_dir")
    src="$orb_dir/lib.or"
    [ -f "$src" ] || continue
    out="$OUT_DIR/${orb}.md"

    {
        echo "# orb \`$orb\`"
        echo ""
        # First leading comment block describes the orb itself.
        awk '/^#/{ sub(/^# ?/, ""); print; next } { exit }' "$src"
        echo ""
        echo "## Public functions"
        echo ""
    } > "$out"

    # Find each `pub fn` line and the comment block above it.
    awk '
        /^# / { block = block "\n" substr($0, 3) ; next }
        /^pub fn/ {
            sub(/:$/, "", $0)
            doc = block; sub(/^\n/, "", doc)
            print "### `" $0 "`"
            print ""
            if (doc != "") print doc
            print ""
            block = ""; next
        }
        /^$/ { next }
        { block = "" }
    ' "$src" >> "$out"

    echo "- [\`$orb\`](${orb}.md)" >> "$INDEX"
done

echo ""
echo "Generated docs for $(ls "$OUT_DIR"/*.md | wc -l) orbs in $OUT_DIR"
