name = "compile_or"
version = "0.1.0"

[orbs]
orion_lex = "path:../../orbs/orion_lex"
orion_parse = "path:../../orbs/orion_parse"
orion_ir = "path:../../orbs/orion_ir"
orion_ast_to_ir = "path:../../orbs/orion_ast_to_ir"
orion_emit_llvm = "path:../../orbs/orion_emit_llvm"
io = "*"
fs = "*"
bytes = "*"
time = "*"
process = "*"
