#!/bin/bash
# bundle_app.sh - flatten an app and every orb it uses into ONE .or file.
#
# The wasm backend compiles a single source; it has no orb loader. A program
# that lives across a dozen orbs cannot reach it at all - orion.exe says
# "orbs 0" and then reports every function in every orb as unknown, which
# reads like a backend that cannot lower them when really it never saw them.
#
# This is bundle_orbs.sh generalised: instead of a hard-coded list of the
# compiler's own orbs, it follows the `use` lines out of the app and out of
# each orb it pulls in, depth first, and writes them out in dependency order.
#
#   bash tools/bundle_app.sh <app-dir> <out.or> [extra-orb-root ...]
#
# Orb roots are searched in order; orion/orbs is always searched last.
set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
APP="${1:?usage: bundle_app.sh <app-dir> <out.or> [orb-root ...]}"
OUT="${2:?}"
shift 2
ROOTS=("$@" "$ROOT/orbs")
OUTDIR=$(cd "$(dirname "$OUT")" && pwd)
ASSETS="$OUTDIR/assets"
mkdir -p "$ASSETS"

find_orb() {
    for r in "${ROOTS[@]}"; do
        [ -f "$r/$1/lib.or" ] && { echo "$r/$1/lib.or"; return 0; }
    done
    return 1
}

SEEN=""
ORDER=()

# Depth first, so an orb is written after everything it uses.
walk() {
    case " $SEEN " in *" $1 "*) return 0;; esac
    SEEN="$SEEN $1"
    local lib dep
    lib=$(find_orb "$1") || return 0    # not on disk: a builtin, nothing to bundle
    while read -r dep; do
        [ -n "$dep" ] && walk "$dep"
    done < <(grep -h '^use ' "$lib" | sed 's/^use //' | tr -d '\r' | sort -u)
    ORDER+=("$lib")
}

APP_SRC=$(ls "$APP"/src/*.or 2>/dev/null || ls "$APP"/*.or 2>/dev/null)
[ -n "$APP_SRC" ] || { echo "no .or sources under $APP"; exit 1; }
for f in $APP_SRC; do
    while read -r dep; do
        [ -n "$dep" ] && walk "$dep"
    done < <(grep -h '^use ' "$f" | sed 's/^use //' | tr -d '\r' | sort -u)
done

# `embed "assets/x.ttf"` is read relative to the FILE it is written in, and
# an absolute path gets that directory glued in FRONT of it - so there is no
# path that works from a bundle sitting somewhere else. The assets are copied
# next to the bundle instead and the paths rewritten to sit beside it.
# Without this the parser leaves an error node where the font should be, and
# the backend then refuses the whole program without ever saying "embed".
RAW="$OUT.raw"
: > "$RAW"

copy_embeds() {           # $1 = source file; writes its lines to $RAW
    local dir=$(dirname "$1")
    local line rel flat
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            *'embed "'*)
                rel=$(printf '%s\n' "$line" | sed -E 's#.*embed "([^"]*)".*#\1#')
                if [ -f "$dir/$rel" ]; then
                    flat=$(basename "$rel")
                    cp -f "$dir/$rel" "$ASSETS/$flat"
                    printf '%s\n' "$line" | sed -E "s#embed \"[^\"]*\"#embed \"assets/$flat\"#" >> "$RAW"
                else
                    printf '%s\n' "$line" >> "$RAW"
                fi ;;
            'use '*) ;;
            *) printf '%s\n' "$line" >> "$RAW" ;;
        esac
    done < "$1"
}

for lib in "${ORDER[@]}"; do
    printf '# ===== %s =====\n' "$(basename "$(dirname "$lib")")" >> "$RAW"
    copy_embeds "$lib"
    printf '\n' >> "$RAW"
done
printf '# ===== app =====\n' >> "$RAW"
for f in $APP_SRC; do copy_embeds "$f"; done

# Two orbs may each define a private helper of the same name - legal while
# they are apart, a clash the moment they are flattened. The first definition
# wins; the later one is dropped along with its body.
{
    printf '# Auto-generated by tools/bundle_app.sh - %s and every orb it uses.\n\n' "$APP"
    awk '
        /^(public )?define [A-Za-z_][A-Za-z_0-9]*\(/ {
            name = $0
            sub(/^(public )?define /, "", name)
            sub(/\(.*/, "", name)
            # How many parameters it takes. Two definitions of one name
            # with the SAME shape are almost always the same small helper
            # written twice, and keeping the first is harmless. Different
            # shapes are two different functions, and letting one answer the
            # calls meant for the other is a bug that surfaces much later as
            # a wasm module that will not validate, or a trap nobody can
            # place. That one is refused here instead.
            args = $0
            sub(/^[^(]*\(/, "", args)
            sub(/\).*/, "", args)
            if (args == "") { n = 0 } else { t = args; gsub(/[^,]/, "", t); n = length(t) + 1 }
            if (name in seen && seen[name] != n) {
                print "bundle: ERROR - two different " name ": one takes " seen[name] " arguments, one takes " n ". Rename one of them." > "/dev/stderr"
                bad = 1
            }
            if (name in seen) {
                print "bundle: dropped a second " name " (the first one wins)" > "/dev/stderr"
                skip = 1; next
            }
            seen[name] = n; skip = 0; print; next
        }
        # Any other line that starts in column one ends the skipped body.
        /^[^ \t]/ { skip = 0 }
        !skip { print }
        END { if (bad) exit 1 }
    ' "$RAW"
} > "$OUT"
rm -f "$RAW"

echo "bundled $(wc -l < "$OUT") lines into $OUT (assets in $ASSETS)"
