#!/usr/bin/env bash
# migrate_aliases.sh — rewrite the whole .or corpus onto the canonical keywords,
# so the transition aliases can be retired from the parser.
#
#   for  -> loop        (`for x in xs:`, `for i, v in xs:`, `for:`, `= for x in`)
#   data -> type        (product decls: `data P: x: int`)
#   enum -> type        (sum decls: `enum Tile: A, B` and the indented form)
#
# Only line-anchored declaration/statement positions are touched: a comment
# (`# for each`) starts with `#`, and the compiler's own `value == "for"` string
# comparisons are mid-line, so neither matches. `data`/`enum` require a
# colon-terminated type name after them, so a variable named `data` is safe.
#
#   bash tools/migrate_aliases.sh [--dry]
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"   # the llstudios tree, not just orion
DRY=0
[ "${1:-}" = "--dry" ] && DRY=1

# dist/ holds GENERATED bundles (regenerated by self_bootstrap) and seed/ holds
# the checked-in bootstrap binary's inputs — neither is hand-edited source.
files=$(find "$ROOT" -name "*.or" \
    -not -path "*/_archive/*" -not -path "*/target/*" -not -path "*/build/*" \
    -not -path "*/orion/dist/*" -not -path "*/seed/*")

changed=0
lines=0
for f in $files; do
    before=$(md5sum "$f" | cut -d' ' -f1)
    out=$(sed -E \
        -e 's/^([[:space:]]*)for:/\1loop:/' \
        -e 's/^([[:space:]]*)for ([A-Za-z_])/\1loop \2/' \
        -e 's/= for ([A-Za-z_])/= loop \1/' \
        -e 's/^([[:space:]]*)(pub )?data ([A-Za-z_][A-Za-z_0-9]*(<[^>]*>)?:)/\1\2type \3/' \
        -e 's/^([[:space:]]*)(pub )?enum ([A-Za-z_][A-Za-z_0-9]*(<[^>]*>)?:)/\1\2type \3/' \
        "$f")
    after=$(printf '%s' "$out" | md5sum | cut -d' ' -f1)
    # md5 of sed output vs file differs by the trailing newline, so compare the
    # rewritten text against the original text read the same way.
    orig=$(cat "$f")
    [ "$out" = "$orig" ] && continue
    n=$(diff <(printf '%s\n' "$orig") <(printf '%s\n' "$out") | grep -c '^>')
    lines=$((lines + n))
    changed=$((changed + 1))
    if [ "$DRY" = "0" ]; then
        printf '%s\n' "$out" > "$f"
    else
        printf "  %s (%s lines)\n" "${f#$ROOT/}" "$n"
    fi
done

echo "migrated $changed files, $lines lines"
