# Generate scripts_embed.c — strong overrides for the weak
# orion_embedded_has/text defaults in orion_rt.c. Byte arrays, so any
# content embeds without escaping.
#
# H1: every text crossing into Orion carries [hash:i64 LE][len:i64 LE]
# BEFORE the byte pointer — d$i arrays bake the header and accessors
# return d$i+16. Hash = polynomial base 131 seed 5381 mod 1e9+7,
# identical to orion_text_hash, 0 remapped to 1.
#
# Usage: embed_assets.ps1 -Out scripts_embed.c -Files cubsy.json,scripts\board.astra,...
# Paths are stored EXACTLY as passed (games look them up with the same
# relative paths they use for file reads) but with backslashes
# normalized to forward slashes.
param(
    [Parameter(Mandatory)] [string]$Out,
    [Parameter(Mandatory)] [string[]]$Files
)
# cmd passes the list as one comma-joined string — split it back.
$Files = $Files | ForEach-Object { $_ -split ',' } | Where-Object { $_ -ne '' }

function HeaderBytes([byte[]]$bytes) {
    [long]$h = 5381
    foreach ($b in $bytes) { $h = ($h * 131 + $b) % 1000000007 }
    if ($h -eq 0) { $h = 1 }
    $out = New-Object System.Collections.Generic.List[string]
    [long]$hv = $h
    for ($k = 0; $k -lt 8; $k++) { [void]$out.Add(($hv -band 0xFF)); $hv = $hv -shr 8 }
    [long]$lv = $bytes.Length
    for ($k = 0; $k -lt 8; $k++) { [void]$out.Add(($lv -band 0xFF)); $lv = $lv -shr 8 }
    return [string]::Join(',', $out)
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* generated by embed_assets.ps1 - do not edit */")
[void]$sb.AppendLine("#include <string.h>")
[void]$sb.AppendLine("static const char e_empty[] = {5,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};")
$i = 0
foreach ($f in $Files) {
    $bytes = [System.IO.File]::ReadAllBytes($f)
    $key = $f.Replace('\', '/')
    [void]$sb.AppendLine("static const char p$i[] = `"$key`";")
    $hexh = HeaderBytes $bytes
    if ($bytes.Length -eq 0) {
        [void]$sb.AppendLine("static const char d$i[] = {$hexh,0};")
    } else {
        $hex = [string]::Join(',', $bytes)
        [void]$sb.AppendLine("static const char d$i[] = {$hexh,$hex,0};")
    }
    $i++
}
[void]$sb.AppendLine("long long orion_embedded_has(const char *path) {")
for ($j = 0; $j -lt $i; $j++) {
    [void]$sb.AppendLine("    if (strcmp(path, p$j) == 0) return 1;")
}
[void]$sb.AppendLine("    return 0;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("const char *orion_embedded_text(const char *path) {")
for ($j = 0; $j -lt $i; $j++) {
    [void]$sb.AppendLine("    if (strcmp(path, p$j) == 0) return d$j + 16;")
}
[void]$sb.AppendLine("    return e_empty + 16;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("const char *orion_embedded_data(const char *path, long long *size) {")
for ($j = 0; $j -lt $i; $j++) {
    [void]$sb.AppendLine("    if (strcmp(path, p$j) == 0) { if (size) *size = sizeof(d$j) - 17; return d$j + 16; }")
}
[void]$sb.AppendLine("    if (size) *size = 0;")
[void]$sb.AppendLine("    return e_empty + 16;")
[void]$sb.AppendLine("}")
$allPaths = ($Files | ForEach-Object { $_.Replace('\', '/') }) -join "`n"
$listBytes = [System.Text.Encoding]::UTF8.GetBytes($allPaths)
$listHdr = HeaderBytes $listBytes
if ($listBytes.Length -eq 0) {
    [void]$sb.AppendLine("static const char lst[] = {$listHdr,0};")
} else {
    $listHex = [string]::Join(',', $listBytes)
    [void]$sb.AppendLine("static const char lst[] = {$listHdr,$listHex,0};")
}
[void]$sb.AppendLine("const char *orion_embedded_list(void) {")
[void]$sb.AppendLine("    return lst + 16;")
[void]$sb.AppendLine("}")
[System.IO.File]::WriteAllText($Out, $sb.ToString())
Write-Host "embedded $i assets -> $Out"
