# Generate scripts_embed.c — strong overrides for the weak
# orion_embedded_has/text defaults in orion_rt.c. Byte arrays, so any
# content embeds without escaping.
#
# Usage: embed_assets.ps1 -Out scripts_embed.c -Files cubsy.json,scripts\board.astra,...
# Paths are stored EXACTLY as passed (games look them up with the same
# relative paths they use for file reads) but with backslashes
# normalized to forward slashes.
param(
    [Parameter(Mandatory)] [string]$Out,
    [Parameter(Mandatory)] [string[]]$Files
)
# cmd passes the list as one comma-joined string — split it back.
$Files = $Files | ForEach-Object { $_ -split ',' } | Where-Object { $_ -ne '' }
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* generated by embed_assets.ps1 - do not edit */")
[void]$sb.AppendLine("#include <string.h>")
$i = 0
foreach ($f in $Files) {
    $bytes = [System.IO.File]::ReadAllBytes($f)
    $key = $f.Replace('\', '/')
    [void]$sb.AppendLine("static const char p$i[] = `"$key`";")
    $hex = ($bytes | ForEach-Object { $_ }) -join ','
    [void]$sb.AppendLine("static const char d$i[] = {$hex,0};")
    $i++
}
[void]$sb.AppendLine("long long orion_embedded_has(const char *path) {")
for ($j = 0; $j -lt $i; $j++) {
    [void]$sb.AppendLine("    if (strcmp(path, p$j) == 0) return 1;")
}
[void]$sb.AppendLine("    return 0;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("const char *orion_embedded_text(const char *path) {")
for ($j = 0; $j -lt $i; $j++) {
    [void]$sb.AppendLine("    if (strcmp(path, p$j) == 0) return d$j;")
}
[void]$sb.AppendLine("    return `"`";")
[void]$sb.AppendLine("}")
[System.IO.File]::WriteAllText($Out, $sb.ToString())
Write-Host "embedded $i assets -> $Out"
